### PR TITLE
if seconds = 0 freeze the alert display

### PR DESCRIPTION
**Pull request by eggggger**

### CODE REVIEW

**Comment by jaredreich** [comment]
Good idea. Will implement. By freeze I'm assuming you mean it will remain up until clicked or escape or enter is pressed.

**Comment by eggggger** [comment]
True ;)
I think it requires the user to see the message after confirmation close it (translation by google)

**Comment by serhatdurum** [comment]
:+1:

**Comment by crzidea** [comment]
👍

**Comment by dengyaolong** [comment]
👍

**Comment by roccomuso** [comment]
I was looking for the same feature. If seconds === 0 alert doesn't go away.

**Pull request closed without merging**
