### PR TITLE
IE8 support

### PR DESCRIPTION
**Pull request by ebersys**
This is the only function preventing from using in IE8

### CODE REVIEW

**Comment by connorjburton** [comment]
Is addEventListener not working on the latest version of notie.JS on ie8? I PR'd a polyfill that got merged recently but wondering if its been put under the event listener which is causing the issue.

Also this PR isn't actually doing anything, as you are declaring the variable but not using it.

**Comment by connorjburton** [comment]
#49 #30

**Comment by ebersys** [comment]
oh yeah, that should fix it, this was before that was in place I guess, and apparently I messed up the code, not adding the next line to use the fix
I'll test the latest again on IE8

**Comment by nilliams** [comment]
I don't think this should have been closed as:

1. The polyfill for addEventListener is still below the first time this is used, so this doesn't work in IE8 as it throws an error on the first use.

2. There's also a reference to (capital W) `Window.addEventListener` here: https://github.com/jaredreich/notie.js/blob/master/notie.js#L135 -- As this doesn't get properly polyfilled this also throws an error in IE8 even after the polyfill in (1) has been moved to the right place.

3. You have un-polyfilled use of `Function.prototype.bind()` for the 'resize' events in 4 places I think (here's one: https://github.com/jaredreich/notie.js/blob/master/notie.js#L198). This obviously doesn't work in IE8.

Could you re-open please. I can prepare a PR as I just fixed these things today. There is also a CSS issue in IE8 with the split-button as well though (the 2 buttons wrap onto 2 lines) which I'm yet to look at.

**Pull request closed without merging**
