### PR TITLE
add no_callback to confirm

### PR DESCRIPTION
**Pull request by benjaminaaron**
addresses half of #18

### CODE REVIEW

**Comment by ebersys** [comment]
yes please

**Comment by rzorzal** [comment]
This works for me. Thanks.

**Comment by akshayKMR** [comment]
If you are trying to force a choice on the user. then clicking anywhere else on the body dismisses the confirm and no_callback doesn't fire. anyway I can force a choice when using notie?

**Comment by akshayKMR** [comment]
found it in config.

**Pull request closed without merging**
